version: "3.8"

services:
  mysql:
    image: mysql
    container_name: my-mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 123456aA@
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    name: mysql_Data
