services:
  redis:
    image: redis
    container_name: redis_db
    environment:
      REDIS_PASSWORD: 123456aA@
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/redis/data
    restart: no

volumes:
  redis_data:
    name: redis_data
